apiVersion: apps/v1
kind: Deployment
metadata:
  name: hatoon-app
  namespace: mine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hatoon-app
  template:
    metadata:
      labels:
        app: hatoon-app
    spec:
      containers:
      - name: my-app-container
        image: my-app-image
        ports:
        - containerPort: 8089
        envFrom:
        - secretRef:
            name: my-secret
